"""LLM-grounded audit report builder — narration, never new inference.

For every DECLINE / MANUAL_REVIEW decision the platform generates a
human-readable audit report. The report is **grounded in the SHAP output
the platform already computes**: the LLM receives only the model score, the
decision/tier, the already-computed top SHAP drivers + one-sentence
summary, and non-sensitive historical context (amount vs typical pattern).
It never sees raw PII or the full 400-feature vector, and it is never asked
to make a new inference — its job is narration.

Failure mode this guards against
--------------------------------
Automated systems that auto-block based on "abnormal activity" signals at
scale, with no fast human-reviewable explanation and no fast reversal path,
cause mass false positives. The report is the fast-reviewable explanation;
the reversal path lives in the review console (``POST /api/review/{id}/appeal``).

Design
------
* :func:`build_report_context` — assemble the exact non-sensitive fields
  that may be injected into the prompt.
* :func:`build_prompt` — the prompt template with those fields injected.
* :func:`parse_llm_response` — extract + validate the structured JSON the
  model returns; garbage → ``None`` → template fallback.
* :func:`build_template_report` — deterministic, LLM-free fallback that
  produces the same JSON schema, so a report is **always** available even
  with no LLM configured.
* :func:`build_report` — final assembly: local identity fields (report id,
  transaction id, timestamp, versions, AI footer) are filled by the
  platform, never by the LLM.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

#: Mandatory footer on every report (hard-coded, never overridden).
AI_FOOTER: str = "Generated by AI — subject to human review."

#: Top-level keys the LLM is expected to produce (narration only).
LLM_KEYS: tuple[str, ...] = (
    "executive_summary",
    "risk_score",
    "drivers",
    "historical_context",
    "recommended_action",
)

#: The report's JSON schema, documented for parsers and storage.
REPORT_SCHEMA: dict[str, Any] = {
    "report_id": "str — platform-assigned",
    "transaction_id": "str — platform-assigned",
    "generated_at": "ISO-8601 UTC",
    "model_version": "str",
    "policy_version": "str",
    "decision": "APPROVE | MANUAL_REVIEW | DECLINE",
    "score": "float — model fraud probability",
    "risk_tier": "str — low | medium | high",
    "thresholds": {"review_above": 0.15, "decline_above": 0.5},
    "executive_summary": "str — 2-3 sentences, plain language",
    "risk_score": {
        "probability": "float",
        "band": "str",
        "thresholds_used": {"review_above": 0.15, "decline_above": 0.5},
    },
    "drivers": [
        {
            "feature": "str",
            "label": "str",
            "value_text": "str",
            "typical_text": "str",
            "contribution": "float",
            "direction": "fraud | safe",
            "narration": "str — one plain-language sentence",
        }
    ],
    "historical_context": "str — amount vs typical, if available",
    "recommended_action": "str",
    "ai_disclaimer": "Generated by AI — subject to human review.",
}


def _amount_context(record: dict[str, Any]) -> tuple[float | None, float | None]:
    """Pull TransactionAmt (value, typical) out of the reason codes."""
    for driver in record.get("reason_codes") or []:
        if driver.get("feature") == "TransactionAmt":
            value = driver.get("value")
            typical = driver.get("typical")
            if isinstance(value, (int, float)) and isinstance(typical, (int, float)):
                return float(value), float(typical)
            return None, None
    return None, None


def build_report_context(record: dict[str, Any]) -> dict[str, Any]:
    """Assemble the non-sensitive fields allowed into the LLM prompt.

    Parameters
    ----------
    record:
        One audit record as returned by ``api.store.get_decision``.

    Returns a dict containing only: score, decision, risk tier, thresholds,
    the top-5 SHAP drivers (label + value/typical text + contribution +
    direction), the existing one-sentence summary, and amount context.
    """
    drivers = (record.get("reason_codes") or [])[:5]
    thresholds = record.get("thresholds") or {}
    amount, amount_typical = _amount_context(record)
    return {
        "score": float(record.get("score") or 0.0),
        "decision": str(record.get("decision") or "APPROVE"),
        "risk_tier": str(record.get("risk_tier") or "low"),
        "review_above": thresholds.get("review_above", 0.15),
        "decline_above": thresholds.get("decline_above", 0.50),
        "summary": str(record.get("summary") or ""),
        "drivers": [
            {
                "feature": d.get("feature"),
                "label": d.get("label", d.get("feature")),
                "value_text": d.get("value_text"),
                "typical_text": d.get("typical_text"),
                "contribution": float(d.get("contribution") or 0.0),
                "direction": d.get("direction", "safe"),
            }
            for d in drivers
            if d.get("feature")
        ],
        "amount": amount,
        "amount_typical": amount_typical,
    }


def build_prompt(context: dict[str, Any]) -> str:
    """The exact prompt template with the allowed fields injected."""
    driver_lines = "\n".join(
        f"- {d['label']}: value {d['value_text']} (typical {d['typical_text']}), "
        f"contribution {d['contribution']:.4f} -> pushes toward {d['direction']}"
        for d in context.get("drivers", [])
    )
    amount = context.get("amount")
    typical = context.get("amount_typical")
    if amount is not None and typical and typical > 0:
        ratio = amount / typical
        amount_note = f"amount ${amount:,.0f} vs typical ${typical:,.0f} ({ratio:.1f}x typical)"
    elif amount is not None:
        amount_note = f"amount ${amount:,.0f}"
    else:
        amount_note = "amount not among the top drivers"

    schema_thresholds = (
        '    "thresholds_used": {{"review_above": {}, "decline_above": {}}}'
    ).format(context["review_above"], context["decline_above"])
    schema_json = "\n".join(
        [
            "{",
            '  "executive_summary": "2-3 sentences plain-language summary of '
            'why this decision was made",',
            '  "risk_score": {',
            '    "probability": {},'.format(context["score"]),
            '    "band": "{}",'.format(context["risk_tier"]),
            schema_thresholds,
            "  },",
            '  "drivers": [',
            "    {",
            '      "feature": "feature name",',
            '      "label": "human label",',
            '      "value_text": "value text",',
            '      "typical_text": "typical text",',
            '      "contribution": 0.0,',
            '      "direction": "fraud",',
            '      "narration": "one plain-language sentence per driver"',
            "    }",
            "  ],",
            '  "historical_context": "one sentence about how the transaction amount '
            'compares to the typical pattern",',
            '  "recommended_action": "one sentence with the recommended next step"',
            "}",
        ]
    )

    return f"""You are a fraud-analysis report writer. You are given ONLY model
output and SHAP explanations that were already computed. Your job is to write
a clear, human-readable audit report in JSON. Do NOT invent facts, do NOT make
new risk assessments, do NOT mention features that are not listed. If the
drivers list is empty, say the model could not be explained.

Facts given (narration only):
- Fraud probability: {context['score']:.4f}
- Decision: {context['decision']} (risk tier {context['risk_tier']})
- Policy thresholds: review at {context['review_above']}, decline at {context['decline_above']}
- Existing one-sentence summary: {context['summary'] or '(none)'}
- Top SHAP drivers:
{driver_lines or '- (none)'}
- Historical context: {amount_note}

Respond with ONLY a JSON object matching exactly this schema:
{schema_json}
Keep the driver narration grounded strictly in the listed values."""


def parse_llm_response(text: str) -> dict[str, Any] | None:
    """Extract and validate the JSON object from an LLM response.

    Tolerates code fences and surrounding prose; requires all
    :data:`LLM_KEYS` to be present and ``drivers`` to be a list of dicts.
    Returns ``None`` on any failure so callers fall back to the template.
    """
    if not text:
        return None
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        start = cleaned.index("{")
        end = cleaned.rindex("}")
        data = json.loads(cleaned[start : end + 1])
    except (ValueError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict) or not all(key in data for key in LLM_KEYS):
        return None
    drivers = data.get("drivers")
    if not isinstance(drivers, list) or not all(isinstance(d, dict) for d in drivers):
        return None
    data["drivers"] = [
        {
            "feature": str(d.get("feature", "")),
            "label": str(d.get("label", d.get("feature", ""))),
            "value_text": str(d.get("value_text", "")),
            "typical_text": str(d.get("typical_text", "")),
            "contribution": float(d.get("contribution", 0.0)),
            "direction": "fraud" if d.get("direction") == "fraud" else "safe",
            "narration": str(d.get("narration", "")),
        }
        for d in drivers
    ]
    return data


def _narrate_driver(driver: dict[str, Any]) -> str:
    label = driver.get("label", driver.get("feature", "feature"))
    value = driver.get("value_text")
    typical = driver.get("typical_text")
    direction = driver.get("direction")
    if direction == "fraud":
        if value in (None, "missing") or typical in (None, "missing"):
            return f"{label} is missing/unknown to the model, which raises risk."
        return f"{label} at {value} (typical {typical}) pushes the score toward fraud."
    if value in (None, "missing") or typical in (None, "missing"):
        return f"{label} being unknown lowers risk."
    return f"{label} at {value} (typical {typical}) is consistent with safe transactions."


def build_template_report(context: dict[str, Any]) -> dict[str, Any]:
    """Deterministic, LLM-free report in the same JSON schema.

    Produced when no LLM is configured or the call fails — a report is
    always available, and its ``source`` is stored as ``template``.
    """
    drivers = context.get("drivers", [])
    amount = context.get("amount")
    typical = context.get("amount_typical")
    if amount is not None and typical and typical > 0:
        ratio = amount / typical
        historical = f"Amount ${amount:,.0f} is {ratio:.1f}x the typical ${typical:,.0f} pattern."
    elif amount is not None:
        historical = f"Amount ${amount:,.0f}; no typical reference available."
    else:
        historical = "Amount was not among the top drivers for this decision."

    decisions = {
        "DECLINE": "Reject or block the transaction; it exceeds the decline threshold.",
        "MANUAL_REVIEW": "Route to manual review and request additional verification.",
        "APPROVE": "Approve; risk is below the review threshold.",
    }
    return {
        "executive_summary": (
            f"Model scored this transaction at {context['score'] * 100:.0f}% "
            f"fraud probability ({context['risk_tier']} risk), leading to "
            f"{context['decision']}. "
            + (
                f"The main signals were: {', '.join(d['label'] for d in drivers[:3])}."
                if drivers
                else "No SHAP drivers were available for this decision."
            )
        ),
        "risk_score": {
            "probability": context["score"],
            "band": context["risk_tier"],
            "thresholds_used": {
                "review_above": context["review_above"],
                "decline_above": context["decline_above"],
            },
        },
        "drivers": [
            {
                "feature": d.get("feature"),
                "label": d.get("label", d.get("feature")),
                "value_text": d.get("value_text"),
                "typical_text": d.get("typical_text"),
                "contribution": d.get("contribution", 0.0),
                "direction": d.get("direction", "safe"),
                "narration": _narrate_driver(d),
            }
            for d in drivers
        ],
        "historical_context": historical,
        "recommended_action": decisions.get(
            context["decision"], "Route to manual review."
        ),
    }


def build_report(
    context: dict[str, Any],
    llm_text: str | None,
    transaction_id: str,
) -> tuple[dict[str, Any], str]:
    """Assemble the final report; returns ``(report, source)``.

    ``source`` is ``"llm"`` when the LLM output parsed cleanly, otherwise
    ``"template"``. Local identity fields and the AI footer are always
    platform-authored — the LLM never writes them.
    """
    parsed = parse_llm_response(llm_text) if llm_text else None
    body = parsed or build_template_report(context)
    source = "llm" if parsed else "template"
    report = {
        "report_id": f"report-{transaction_id}",
        "transaction_id": transaction_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model_version": None,
        "policy_version": None,
        "decision": context["decision"],
        "score": context["score"],
        "risk_tier": context["risk_tier"],
        "thresholds": {
            "review_above": context["review_above"],
            "decline_above": context["decline_above"],
        },
        **body,
        "ai_disclaimer": AI_FOOTER,
    }
    if parsed:
        # keep the LLM's narrative keys only; identity fields stay platform-owned
        for key in LLM_KEYS:
            if key in report:
                del report[key]
        for key in LLM_KEYS:
            report[key] = parsed.get(key)
    return report, source
