import React from 'react';
import { Bot, FileCode } from 'lucide-react';

interface AIDisclaimerProps {
  source?: 'llm' | 'template' | string;
  className?: string;
  children?: React.ReactNode;
}

export const AIDisclaimer: React.FC<AIDisclaimerProps> = ({
  source = 'llm',
  className = '',
  children,
}) => {
  const isLLM = source === 'llm';

  return (
    <div className={`border border-border-subtle rounded-2xl bg-surface-2/60 backdrop-blur-xl p-4 space-y-3 shadow-sm ${className}`}>
      <div className="flex items-center justify-between border-b border-border-subtle/60 pb-2 text-xs font-sans">
        <div className="flex items-center gap-2 text-text-secondary">
          {isLLM ? (
            <Bot className="w-4 h-4 text-apple-blue" />
          ) : (
            <FileCode className="w-4 h-4 text-apple-indigo" />
          )}
          <span className="font-medium">Narrative Generation Source:</span>
          <span className="px-2 py-0.5 rounded-full bg-surface-1 border border-border-subtle font-semibold text-text-primary text-[10px] uppercase">
            {source}
          </span>
        </div>

        <span className="text-text-muted text-[11px] font-mono">
          Auditable Record
        </span>
      </div>

      {children && <div className="text-xs font-sans text-text-primary leading-relaxed">{children}</div>}

      <div className="pt-2 text-[11px] font-sans text-text-muted border-t border-border-subtle/40 flex items-center justify-between">
        <span>Generated by AI — subject to human review.</span>
        <span className="font-mono text-[10px]">ISO 27001 / SOC 2 Type II</span>
      </div>
    </div>
  );
};
