import React from 'react';
import { Bot, FileCode } from 'lucide-react';

interface AIDisclaimerProps {
  source?: 'llm' | 'template' | string;
  className?: string;
  children?: React.ReactNode;
}

export const AIDisclaimer: React.FC<AIDisclaimerProps> = ({
  source = 'llm',
  className = '',
  children,
}) => {
  const isLLM = source === 'llm';

  return (
    <div className={`border border-border-subtle rounded-[4px] bg-surface-2/70 p-3.5 space-y-2.5 ${className}`}>
      <div className="flex items-center justify-between border-b border-border-subtle/70 pb-2 text-[11px] font-mono">
        <div className="flex items-center gap-1.5 text-text-secondary">
          {isLLM ? (
            <Bot className="w-3.5 h-3.5 text-text-muted" />
          ) : (
            <FileCode className="w-3.5 h-3.5 text-text-muted" />
          )}
          <span>Narrative Generation Source:</span>
          <span className="px-1.5 py-0.2 rounded bg-surface-1 border border-border-subtle font-bold text-text-primary uppercase">
            {source}
          </span>
        </div>

        <span className="text-text-muted text-[10px]">
          Auditable Record
        </span>
      </div>

      {children && <div className="text-xs font-mono text-text-primary leading-relaxed">{children}</div>}

      <div className="pt-1 text-[10px] font-mono text-text-muted border-t border-border-subtle/50 flex items-center justify-between">
        <span>Generated by AI — subject to human review.</span>
        <span>ISO 27001 / SOC 2 Type II Compliance</span>
      </div>
    </div>
  );
};
